# Generated by Django 3.0.4 on 2020-04-01 08:20

from django.db import migrations, models
import django.db.models.deletion
import isfahan.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date_published', models.DateField()),
                ('time_published', models.TimeField(null=True)),
                ('area_size', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('publisher_type', models.TextField()),
                ('description', models.TextField()),
                ('uri', models.URLField(null=True)),
                ('datetime_crawled', models.DateTimeField(null=True)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'isfahan_articles',
                'ordering': ['-date_published', '-time_published'],
                'get_latest_by': ['date_published', 'time_published'],
                'default_related_name': 'articles',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('name_english', models.TextField()),
                ('href', models.URLField(null=True)),
            ],
            options={
                'db_table': 'isfahan_locations',
                'ordering': ['name'],
                'unique_together': {('name', 'name_english')},
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(unique=True, validators=[isfahan.validators.phone_validator])),
                ('locations', models.ManyToManyField(related_name='persons', through='isfahan.Article', to='isfahan.Location')),
            ],
            options={
                'db_table': 'isfahan_persons',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('name_english', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'isfahan_categories',
                'ordering': ['name_english'],
                'unique_together': {('name', 'name_english')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='isfahan.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='isfahan.Location'),
        ),
        migrations.AddField(
            model_name='article',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='isfahan.Person'),
        ),
    ]
